#!/bin/bash
## Coptyright 2016 The HongJiang Library Project Authors. All rights reserved.
## Use of this source code is governed by a Apache-style
## license that can be found in the LICNESE file.
##
## Git(Github.com) Common Client Commands.
##
## @authors hjboss <hongjiangproject@gmail.com> 2016-03 $$
## @version 1.0.0
##
GIT=`/usr/bin/which git`
HOST='git@github.com'
NAME='hlibs'
SCRIPT=`basename $0`

case "$1" in
	"add")
		if [ $# -lt 2 ] || [ "$2" == "*" ]; then
			$GIT add --all
		else
			$GIT add "$2"
		fi
	;;

	"ci")
		if [ $# -lt 2 ]; then
			$GIT commit -a -m "Initial commit"
		else
			$GIT commit -a -m "$2"
		fi
		$GIT push -u origin master
	;;

	"co")
		if [ $# -lt 2 ]; then
			echo "版本庫名稱不能空值"
		elif [ $# -eq 2 ]; then
			$GIT clone "$HOST:$NAME/$2.git"
		else
			$GIT clone "$HOST:$2/$3.git"
		fi
	;;

	"rm")
		if [ $# -lt 2 ]; then
			echo "刪除文件名不能空值"
			exit
		fi
		$GIT rm "$2"
	;;

	"up")
		$GIT pull
	;;

	"st")
		$GIT status
	;;

	"help")
		echo "用法: $SCRIPT <subcommand> [args]"
		echo "版本: 1.0.0"
		echo "最常用的子命令:"
		echo "  add 添加文件内容至索引"
		echo "  ci 记录变更到版本库并且更新至github.com"
		echo "  co 将给定名称的版本库克隆到一个新目录"
		echo "  rm 从工作区和索引中删除文件"
		echo "  up 本地分支更新到最新版本"
		echo "  st 显示工作区状态"
	;;

	"version")
		echo "$SCRIPT version 1.0.0"
	;;

	*)
		echo "使用$SCRIPT help得到用法"
	;;
esac

